// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgameclientproto;

public enum E_CLIENT_MSGID {

	E_MSGID_ADDICT__NOTIFY(95),
	E_MSGID_LOGIN_REQ(99),
	E_TABLE_ENTER(101),
	E_TABLE_LEAVE(102),
	E_TABLE_SIT_DOWN(103),
	E_TABLE_STAND_UP(104),
	E_TABLE_RECONNECT(113),
	E_TABLE_PREPARE(114),
	E_TABLE_DISMISS(115),
	E_TABLE_VOTE_DISMISS(116),
	E_TABLE_CHAT_TEXT(117),
	E_TABLE_CHAT_AUDIO(118),
	E_TABLE_KICK_OUT(119),
	E_GAME_ACTION(222);

	private final int value;

	private E_CLIENT_MSGID(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_CLIENT_MSGID convert(int value) {
		for(E_CLIENT_MSGID v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
