// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgameclientproto;

public enum E_PLAYER_STATE {

	E_PLAYER_INITIALIZE(0),
	E_PLAYER_PREPARE(1),
	E_PLAYER_PLAYING(10),
	E_PLAYER_DISCONNECTED(11),
	E_PLAYER_TRUSTEESHIP(12);

	private final int value;

	private E_PLAYER_STATE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_PLAYER_STATE convert(int value) {
		for(E_PLAYER_STATE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
