// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgameclientproto;

public enum E_ROOM_TYPE {

	E_GOLD_COIN(0),
	E_ROOM_CARD(1);

	private final int value;

	private E_ROOM_TYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_ROOM_TYPE convert(int value) {
		for(E_ROOM_TYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
