// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgNotifyPrepare {

	@TarsStructProperty(order = 0, isRequire = true)
	public byte nChairNo = (byte)0;

	public byte getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	public TMsgNotifyPrepare() {
	}

	public TMsgNotifyPrepare(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nChairNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgNotifyPrepare)) {
			return false;
		}
		TMsgNotifyPrepare other = (TMsgNotifyPrepare) obj;
		return (
			TarsUtil.equals(nChairNo, other.nChairNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nChairNo, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.nChairNo = _is.read(nChairNo, 0, true);
	}

}
