// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgHead {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nMsgID = (short)0;
	@TarsStructProperty(order = 1, isRequire = false)
	public int nMsgType = 0;

	public short getNMsgID() {
		return nMsgID;
	}

	public void setNMsgID(short nMsgID) {
		this.nMsgID = nMsgID;
	}

	public int getNMsgType() {
		return nMsgType;
	}

	public void setNMsgType(int nMsgType) {
		this.nMsgType = nMsgType;
	}

	public TMsgHead() {
	}

	public TMsgHead(short nMsgID, int nMsgType) {
		this.nMsgID = nMsgID;
		this.nMsgType = nMsgType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nMsgID);
		result = prime * result + TarsUtil.hashCode(nMsgType);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgHead)) {
			return false;
		}
		TMsgHead other = (TMsgHead) obj;
		return (
			TarsUtil.equals(nMsgID, other.nMsgID) &&
			TarsUtil.equals(nMsgType, other.nMsgType) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nMsgID, 0);
		_os.write(nMsgType, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.nMsgID = _is.read(nMsgID, 0, true);
		this.nMsgType = _is.read(nMsgType, 1, false);
	}

}
