// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgame;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class TarsRoomPrxCallback extends TarsAbstractCallback {

	public abstract void callback_hello(String ret);

	public abstract void callback_onRequest(int ret);

	public abstract void callback_onOffLine(int ret);

}
