// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.jfgame;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TarsRouterPrx {

	public int doPush(long lUid, com.bzw.tars.client.tars.jfgameclientproto.TRespPackage tRespPackage);

	public int doPush(long lUid, com.bzw.tars.client.tars.jfgameclientproto.TRespPackage tRespPackage, @TarsContext java.util.Map<String, String> ctx);

	public void async_doPush(@TarsCallback TarsRouterPrxCallback callback, long lUid, com.bzw.tars.client.tars.jfgameclientproto.TRespPackage tRespPackage);

	public void async_doPush(@TarsCallback TarsRouterPrxCallback callback, long lUid, com.bzw.tars.client.tars.jfgameclientproto.TRespPackage tRespPackage, @TarsContext java.util.Map<String, String> ctx);
}
