// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

public enum EGameMsgType {

	E_NOTIFY_DATA(0),
	E_RESPONE_DATA(1),
	E_RESPALL_DATA(2),
	E_MIXTURE_DATA(3);

	private final int value;

	private EGameMsgType(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static EGameMsgType convert(int value) {
		for(EGameMsgType v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
