// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TData {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nMsgID = (short)0;
	@TarsStructProperty(order = 1, isRequire = true)
	public byte[] vecData = null;

	public short getNMsgID() {
		return nMsgID;
	}

	public void setNMsgID(short nMsgID) {
		this.nMsgID = nMsgID;
	}

	public byte[] getVecData() {
		return vecData;
	}

	public void setVecData(byte[] vecData) {
		this.vecData = vecData;
	}

	public TData() {
	}

	public TData(short nMsgID, byte[] vecData) {
		this.nMsgID = nMsgID;
		this.vecData = vecData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nMsgID);
		result = prime * result + TarsUtil.hashCode(vecData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TData)) {
			return false;
		}
		TData other = (TData) obj;
		return (
			TarsUtil.equals(nMsgID, other.nMsgID) &&
			TarsUtil.equals(vecData, other.vecData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nMsgID, 0);
		_os.write(vecData, 1);
	}

	static byte[] cache_vecData;
	static { 
		cache_vecData = new byte[1];
		byte var_11 = (byte)0;
		cache_vecData[0] = var_11;
	}

	public void readFrom(TarsInputStream _is) {
		this.nMsgID = _is.read(nMsgID, 0, true);
		this.vecData = (byte[]) _is.read(cache_vecData, 1, true);
	}

}
