// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

/**
 * 游戏开始
 * 当前玩家UID，list下标为座次号
 */
@TarsStruct
public class TGamgStart {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<TPlayerInfo> playerInfo = null;

	public java.util.List<TPlayerInfo> getPlayerInfo() {
		return playerInfo;
	}

	public void setPlayerInfo(java.util.List<TPlayerInfo> playerInfo) {
		this.playerInfo = playerInfo;
	}

	public TGamgStart() {
	}

	public TGamgStart(java.util.List<TPlayerInfo> playerInfo) {
		this.playerInfo = playerInfo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(playerInfo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGamgStart)) {
			return false;
		}
		TGamgStart other = (TGamgStart) obj;
		return (
			TarsUtil.equals(playerInfo, other.playerInfo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(playerInfo, 0);
	}

	static java.util.List<TPlayerInfo> cache_playerInfo;
	static { 
		cache_playerInfo = new java.util.ArrayList<TPlayerInfo>();
		TPlayerInfo var_9 = new TPlayerInfo();
		cache_playerInfo.add(var_9);
	}

	public void readFrom(TarsInputStream _is) {
		this.playerInfo = (java.util.List<TPlayerInfo>) _is.read(cache_playerInfo, 0, true);
	}

}
