// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

/**
 * 游戏返回数据
 * =======================
 * 根据EGameMsgType取下列数据，详细见枚举说明
 */
@TarsStruct
public class TGameData {

	@TarsStructProperty(order = 0, isRequire = true)
	public byte eMsgType = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public TData tNotifyData = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public TData tRespOneData = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public java.util.List<TData> vecRespAllData = null;
	@TarsStructProperty(order = 4, isRequire = false)
	public TData tNotifyOnlookerData = null;

	public byte getEMsgType() {
		return eMsgType;
	}

	public void setEMsgType(byte eMsgType) {
		this.eMsgType = eMsgType;
	}

	public TData getTNotifyData() {
		return tNotifyData;
	}

	public void setTNotifyData(TData tNotifyData) {
		this.tNotifyData = tNotifyData;
	}

	public TData getTRespOneData() {
		return tRespOneData;
	}

	public void setTRespOneData(TData tRespOneData) {
		this.tRespOneData = tRespOneData;
	}

	public java.util.List<TData> getVecRespAllData() {
		return vecRespAllData;
	}

	public void setVecRespAllData(java.util.List<TData> vecRespAllData) {
		this.vecRespAllData = vecRespAllData;
	}

	public TData getTNotifyOnlookerData() {
		return tNotifyOnlookerData;
	}

	public void setTNotifyOnlookerData(TData tNotifyOnlookerData) {
		this.tNotifyOnlookerData = tNotifyOnlookerData;
	}

	public TGameData() {
	}

	public TGameData(byte eMsgType, TData tNotifyData, TData tRespOneData, java.util.List<TData> vecRespAllData, TData tNotifyOnlookerData) {
		this.eMsgType = eMsgType;
		this.tNotifyData = tNotifyData;
		this.tRespOneData = tRespOneData;
		this.vecRespAllData = vecRespAllData;
		this.tNotifyOnlookerData = tNotifyOnlookerData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(eMsgType);
		result = prime * result + TarsUtil.hashCode(tNotifyData);
		result = prime * result + TarsUtil.hashCode(tRespOneData);
		result = prime * result + TarsUtil.hashCode(vecRespAllData);
		result = prime * result + TarsUtil.hashCode(tNotifyOnlookerData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGameData)) {
			return false;
		}
		TGameData other = (TGameData) obj;
		return (
			TarsUtil.equals(eMsgType, other.eMsgType) &&
			TarsUtil.equals(tNotifyData, other.tNotifyData) &&
			TarsUtil.equals(tRespOneData, other.tRespOneData) &&
			TarsUtil.equals(vecRespAllData, other.vecRespAllData) &&
			TarsUtil.equals(tNotifyOnlookerData, other.tNotifyOnlookerData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(eMsgType, 0);
		if (null != tNotifyData) {
			_os.write(tNotifyData, 1);
		}
		if (null != tRespOneData) {
			_os.write(tRespOneData, 2);
		}
		if (null != vecRespAllData) {
			_os.write(vecRespAllData, 3);
		}
		if (null != tNotifyOnlookerData) {
			_os.write(tNotifyOnlookerData, 4);
		}
	}

	static TData cache_tNotifyData;
	static { 
		cache_tNotifyData = new TData();
	}
	static TData cache_tRespOneData;
	static { 
		cache_tRespOneData = new TData();
	}
	static java.util.List<TData> cache_vecRespAllData;
	static { 
		cache_vecRespAllData = new java.util.ArrayList<TData>();
		TData var_14 = new TData();
		cache_vecRespAllData.add(var_14);
	}
	static TData cache_tNotifyOnlookerData;
	static { 
		cache_tNotifyOnlookerData = new TData();
	}

	public void readFrom(TarsInputStream _is) {
		this.eMsgType = _is.read(eMsgType, 0, true);
		this.tNotifyData = (TData) _is.read(cache_tNotifyData, 1, false);
		this.tRespOneData = (TData) _is.read(cache_tRespOneData, 2, false);
		this.vecRespAllData = (java.util.List<TData>) _is.read(cache_vecRespAllData, 3, false);
		this.tNotifyOnlookerData = (TData) _is.read(cache_tNotifyOnlookerData, 4, false);
	}

}
