// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

/**
 * 创建房间的基础规则在这里增加，
 * 特殊的规则写成json，放进rules里面
 * 必须满足开放性要求，不做具体限制
 */
@TarsStruct
public class TGameCreate {

	@TarsStructProperty(order = 0, isRequire = true)
	public byte roomType = (byte)0;
	@TarsStructProperty(order = 10, isRequire = true)
	public String rules = "";

	public byte getRoomType() {
		return roomType;
	}

	public void setRoomType(byte roomType) {
		this.roomType = roomType;
	}

	public String getRules() {
		return rules;
	}

	public void setRules(String rules) {
		this.rules = rules;
	}

	public TGameCreate() {
	}

	public TGameCreate(byte roomType, String rules) {
		this.roomType = roomType;
		this.rules = rules;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(roomType);
		result = prime * result + TarsUtil.hashCode(rules);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGameCreate)) {
			return false;
		}
		TGameCreate other = (TGameCreate) obj;
		return (
			TarsUtil.equals(roomType, other.roomType) &&
			TarsUtil.equals(rules, other.rules) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(roomType, 0);
		_os.write(rules, 10);
	}


	public void readFrom(TarsInputStream _is) {
		this.roomType = _is.read(roomType, 0, true);
		this.rules = _is.readString(10, true);
	}

}
