// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

/**
 * 由于该规则由Room创建，所以必须满足开放性要求，不做具体限制
 */
@TarsStruct
public class TGameCreate {

	@TarsStructProperty(order = 0, isRequire = true)
	public String rules = "";

	public String getRules() {
		return rules;
	}

	public void setRules(String rules) {
		this.rules = rules;
	}

	public TGameCreate() {
	}

	public TGameCreate(String rules) {
		this.rules = rules;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(rules);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGameCreate)) {
			return false;
		}
		TGameCreate other = (TGameCreate) obj;
		return (
			TarsUtil.equals(rules, other.rules) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(rules, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.rules = _is.readString(0, true);
	}

}
