// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TGamgStart {

	@TarsStructProperty(order = 0, isRequire = true)
	public java.util.List<java.lang.Long> vecUserID = null;

	public java.util.List<java.lang.Long> getVecUserID() {
		return vecUserID;
	}

	public void setVecUserID(java.util.List<java.lang.Long> vecUserID) {
		this.vecUserID = vecUserID;
	}

	public TGamgStart() {
	}

	public TGamgStart(java.util.List<java.lang.Long> vecUserID) {
		this.vecUserID = vecUserID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(vecUserID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGamgStart)) {
			return false;
		}
		TGamgStart other = (TGamgStart) obj;
		return (
			TarsUtil.equals(vecUserID, other.vecUserID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(vecUserID, 0);
	}

	static java.util.List<java.lang.Long> cache_vecUserID;
	static { 
		cache_vecUserID = new java.util.ArrayList<java.lang.Long>();
		long var_9 = 0L;
		cache_vecUserID.add(var_9);
	}

	public void readFrom(TarsInputStream _is) {
		this.vecUserID = (java.util.List<java.lang.Long>) _is.read(cache_vecUserID, 0, true);
	}

}
