// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPlayerInfo {

	@TarsStructProperty(order = 0, isRequire = true)
	public long userID = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public short nChairNo = (short)0;

	public long getUserID() {
		return userID;
	}

	public void setUserID(long userID) {
		this.userID = userID;
	}

	public short getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(short nChairNo) {
		this.nChairNo = nChairNo;
	}

	public TPlayerInfo() {
	}

	public TPlayerInfo(long userID, short nChairNo) {
		this.userID = userID;
		this.nChairNo = nChairNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userID);
		result = prime * result + TarsUtil.hashCode(nChairNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPlayerInfo)) {
			return false;
		}
		TPlayerInfo other = (TPlayerInfo) obj;
		return (
			TarsUtil.equals(userID, other.userID) &&
			TarsUtil.equals(nChairNo, other.nChairNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(userID, 0);
		_os.write(nChairNo, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.userID = _is.read(userID, 0, true);
		this.nChairNo = _is.read(nChairNo, 1, true);
	}

}
