// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tars.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRespMessage {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nMsgID = (short)0;
	@TarsStructProperty(order = 1, isRequire = true)
	public String sTableNo = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public short nChairIdx = -1;
	@TarsStructProperty(order = 3, isRequire = true)
	public short nTimeout = 0;
	@TarsStructProperty(order = 4, isRequire = true)
	public int eMsgType = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public TGameData stGameData = null;

	public short getNMsgID() {
		return nMsgID;
	}

	public void setNMsgID(short nMsgID) {
		this.nMsgID = nMsgID;
	}

	public String getSTableNo() {
		return sTableNo;
	}

	public void setSTableNo(String sTableNo) {
		this.sTableNo = sTableNo;
	}

	public short getNChairIdx() {
		return nChairIdx;
	}

	public void setNChairIdx(short nChairIdx) {
		this.nChairIdx = nChairIdx;
	}

	public short getNTimeout() {
		return nTimeout;
	}

	public void setNTimeout(short nTimeout) {
		this.nTimeout = nTimeout;
	}

	public int getEMsgType() {
		return eMsgType;
	}

	public void setEMsgType(int eMsgType) {
		this.eMsgType = eMsgType;
	}

	public TGameData getStGameData() {
		return stGameData;
	}

	public void setStGameData(TGameData stGameData) {
		this.stGameData = stGameData;
	}

	public TRespMessage() {
	}

	public TRespMessage(short nMsgID, String sTableNo, short nChairIdx, short nTimeout, int eMsgType, TGameData stGameData) {
		this.nMsgID = nMsgID;
		this.sTableNo = sTableNo;
		this.nChairIdx = nChairIdx;
		this.nTimeout = nTimeout;
		this.eMsgType = eMsgType;
		this.stGameData = stGameData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nMsgID);
		result = prime * result + TarsUtil.hashCode(sTableNo);
		result = prime * result + TarsUtil.hashCode(nChairIdx);
		result = prime * result + TarsUtil.hashCode(nTimeout);
		result = prime * result + TarsUtil.hashCode(eMsgType);
		result = prime * result + TarsUtil.hashCode(stGameData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRespMessage)) {
			return false;
		}
		TRespMessage other = (TRespMessage) obj;
		return (
			TarsUtil.equals(nMsgID, other.nMsgID) &&
			TarsUtil.equals(sTableNo, other.sTableNo) &&
			TarsUtil.equals(nChairIdx, other.nChairIdx) &&
			TarsUtil.equals(nTimeout, other.nTimeout) &&
			TarsUtil.equals(eMsgType, other.eMsgType) &&
			TarsUtil.equals(stGameData, other.stGameData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nMsgID, 0);
		_os.write(sTableNo, 1);
		_os.write(nChairIdx, 2);
		_os.write(nTimeout, 3);
		_os.write(eMsgType, 4);
		if (null != stGameData) {
			_os.write(stGameData, 5);
		}
	}

	static TGameData cache_stGameData;
	static { 
		cache_stGameData = new TGameData();
	}

	public void readFrom(TarsInputStream _is) {
		this.nMsgID = _is.read(nMsgID, 0, true);
		this.sTableNo = _is.readString(1, true);
		this.nChairIdx = _is.read(nChairIdx, 2, true);
		this.nTimeout = _is.read(nTimeout, 3, true);
		this.eMsgType = _is.read(eMsgType, 4, true);
		this.stGameData = (TGameData) _is.read(cache_stGameData, 5, false);
	}

}
