// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tarsgame;

public enum E_GAME_MSGID {

	GAMECREATE(10),
	GAMEPREPARE(11),
	GAMERECONNECT(12),
	GAMESTART(13),
	GAMEFINNISH(14),
	GAMEDISMISS(15),
	GAMERESULT(16),
	GAMEACTION1(51),
	GAMEACTION2(52),
	GAMEACTION3(53),
	GAMEACTION4(54),
	GAMEACTION5(55),
	GAMEACTION6(56),
	GAMEACTION7(57),
	GAMEACTION8(58),
	GAMEACTION9(59);

	private final int value;

	private E_GAME_MSGID(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_GAME_MSGID convert(int value) {
		for(E_GAME_MSGID v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
