// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.tarsgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TRespMessage {

	@TarsStructProperty(order = 1, isRequire = true)
	public int eMsgType = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public TGameData stGameData = null;

	public int getEMsgType() {
		return eMsgType;
	}

	public void setEMsgType(int eMsgType) {
		this.eMsgType = eMsgType;
	}

	public TGameData getStGameData() {
		return stGameData;
	}

	public void setStGameData(TGameData stGameData) {
		this.stGameData = stGameData;
	}

	public TRespMessage() {
	}

	public TRespMessage(int eMsgType, TGameData stGameData) {
		this.eMsgType = eMsgType;
		this.stGameData = stGameData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(eMsgType);
		result = prime * result + TarsUtil.hashCode(stGameData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TRespMessage)) {
			return false;
		}
		TRespMessage other = (TRespMessage) obj;
		return (
			TarsUtil.equals(eMsgType, other.eMsgType) &&
			TarsUtil.equals(stGameData, other.stGameData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(eMsgType, 1);
		if (null != stGameData) {
			_os.write(stGameData, 2);
		}
	}

	static TGameData cache_stGameData;
	static { 
		cache_stGameData = new TGameData();
	}

	public void readFrom(TarsInputStream _is) {
		this.eMsgType = _is.read(eMsgType, 1, true);
		this.stGameData = (TGameData) _is.read(cache_stGameData, 2, false);
	}

}
