// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgame;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TarsRoomServant {

	public String hello();

	public int onRequest(long lUin, byte[] sMsgPack, String sCurServantAddr, TClientParam stClientParam, TUserBaseInfoExt stUerBaseInfo);

	public int onOffLine(long lUin);
}
