// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgame;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TUserBaseInfoExt {

	@TarsStructProperty(order = 0, isRequire = true)
	public int num = 0;

	public int getNum() {
		return num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public TUserBaseInfoExt() {
	}

	public TUserBaseInfoExt(int num) {
		this.num = num;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(num);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TUserBaseInfoExt)) {
			return false;
		}
		TUserBaseInfoExt other = (TUserBaseInfoExt) obj;
		return (
			TarsUtil.equals(num, other.num) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(num, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.num = _is.read(num, 0, true);
	}

}
