// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

public enum E_MSGTYPE {

	E_REQUEST(0),
	E_RESPONSE(1),
	E_NOTIFY(2);

	private final int value;

	private E_MSGTYPE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_MSGTYPE convert(int value) {
		for(E_MSGTYPE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
