// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

public interface JFGameClientProtoConst {

	public static final int iVersion = 1;
}
