// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TGamePackage {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nMsgID = (short)0;

	public short getNMsgID() {
		return nMsgID;
	}

	public void setNMsgID(short nMsgID) {
		this.nMsgID = nMsgID;
	}

	public TGamePackage() {
	}

	public TGamePackage(short nMsgID) {
		this.nMsgID = nMsgID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nMsgID);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TGamePackage)) {
			return false;
		}
		TGamePackage other = (TGamePackage) obj;
		return (
			TarsUtil.equals(nMsgID, other.nMsgID) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nMsgID, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.nMsgID = _is.read(nMsgID, 0, true);
	}

}
