// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgReqReconnectTable {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sTableNo = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String sSign = "";

	public String getSTableNo() {
		return sTableNo;
	}

	public void setSTableNo(String sTableNo) {
		this.sTableNo = sTableNo;
	}

	public String getSSign() {
		return sSign;
	}

	public void setSSign(String sSign) {
		this.sSign = sSign;
	}

	public TMsgReqReconnectTable() {
	}

	public TMsgReqReconnectTable(String sTableNo, String sSign) {
		this.sTableNo = sTableNo;
		this.sSign = sSign;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sTableNo);
		result = prime * result + TarsUtil.hashCode(sSign);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgReqReconnectTable)) {
			return false;
		}
		TMsgReqReconnectTable other = (TMsgReqReconnectTable) obj;
		return (
			TarsUtil.equals(sTableNo, other.sTableNo) &&
			TarsUtil.equals(sSign, other.sSign) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sTableNo, 0);
		_os.write(sSign, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.sTableNo = _is.readString(0, true);
		this.sSign = _is.readString(1, true);
	}

}
