// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgReqLeaveTable {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sTableNo = "";

	public String getSTableNo() {
		return sTableNo;
	}

	public void setSTableNo(String sTableNo) {
		this.sTableNo = sTableNo;
	}

	public TMsgReqLeaveTable() {
	}

	public TMsgReqLeaveTable(String sTableNo) {
		this.sTableNo = sTableNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sTableNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgReqLeaveTable)) {
			return false;
		}
		TMsgReqLeaveTable other = (TMsgReqLeaveTable) obj;
		return (
			TarsUtil.equals(sTableNo, other.sTableNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sTableNo, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.sTableNo = _is.readString(0, true);
	}

}
