// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPackage {

	@TarsStructProperty(order = 0, isRequire = true)
	public int iVersion = 1;
	@TarsStructProperty(order = 1, isRequire = true)
	public TUid stUid = null;
	@TarsStructProperty(order = 2, isRequire = true)
	public int iGameID = 0;
	@TarsStructProperty(order = 3, isRequire = true)
	public String sRoomID = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public int iRoomServerID = 0;
	@TarsStructProperty(order = 5, isRequire = true)
	public int iSequence = 0;
	@TarsStructProperty(order = 6, isRequire = true)
	public int iFlag = 0;
	@TarsStructProperty(order = 7, isRequire = true)
	public java.util.List<TMsgHead> vecMsgHead = null;
	@TarsStructProperty(order = 8, isRequire = true)
	public java.util.List<byte[]> vecMsgData = null;

	public int getIVersion() {
		return iVersion;
	}

	public void setIVersion(int iVersion) {
		this.iVersion = iVersion;
	}

	public TUid getStUid() {
		return stUid;
	}

	public void setStUid(TUid stUid) {
		this.stUid = stUid;
	}

	public int getIGameID() {
		return iGameID;
	}

	public void setIGameID(int iGameID) {
		this.iGameID = iGameID;
	}

	public String getSRoomID() {
		return sRoomID;
	}

	public void setSRoomID(String sRoomID) {
		this.sRoomID = sRoomID;
	}

	public int getIRoomServerID() {
		return iRoomServerID;
	}

	public void setIRoomServerID(int iRoomServerID) {
		this.iRoomServerID = iRoomServerID;
	}

	public int getISequence() {
		return iSequence;
	}

	public void setISequence(int iSequence) {
		this.iSequence = iSequence;
	}

	public int getIFlag() {
		return iFlag;
	}

	public void setIFlag(int iFlag) {
		this.iFlag = iFlag;
	}

	public java.util.List<TMsgHead> getVecMsgHead() {
		return vecMsgHead;
	}

	public void setVecMsgHead(java.util.List<TMsgHead> vecMsgHead) {
		this.vecMsgHead = vecMsgHead;
	}

	public java.util.List<byte[]> getVecMsgData() {
		return vecMsgData;
	}

	public void setVecMsgData(java.util.List<byte[]> vecMsgData) {
		this.vecMsgData = vecMsgData;
	}

	public TPackage() {
	}

	public TPackage(int iVersion, TUid stUid, int iGameID, String sRoomID, int iRoomServerID, int iSequence, int iFlag, java.util.List<TMsgHead> vecMsgHead, java.util.List<byte[]> vecMsgData) {
		this.iVersion = iVersion;
		this.stUid = stUid;
		this.iGameID = iGameID;
		this.sRoomID = sRoomID;
		this.iRoomServerID = iRoomServerID;
		this.iSequence = iSequence;
		this.iFlag = iFlag;
		this.vecMsgHead = vecMsgHead;
		this.vecMsgData = vecMsgData;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iVersion);
		result = prime * result + TarsUtil.hashCode(stUid);
		result = prime * result + TarsUtil.hashCode(iGameID);
		result = prime * result + TarsUtil.hashCode(sRoomID);
		result = prime * result + TarsUtil.hashCode(iRoomServerID);
		result = prime * result + TarsUtil.hashCode(iSequence);
		result = prime * result + TarsUtil.hashCode(iFlag);
		result = prime * result + TarsUtil.hashCode(vecMsgHead);
		result = prime * result + TarsUtil.hashCode(vecMsgData);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPackage)) {
			return false;
		}
		TPackage other = (TPackage) obj;
		return (
			TarsUtil.equals(iVersion, other.iVersion) &&
			TarsUtil.equals(stUid, other.stUid) &&
			TarsUtil.equals(iGameID, other.iGameID) &&
			TarsUtil.equals(sRoomID, other.sRoomID) &&
			TarsUtil.equals(iRoomServerID, other.iRoomServerID) &&
			TarsUtil.equals(iSequence, other.iSequence) &&
			TarsUtil.equals(iFlag, other.iFlag) &&
			TarsUtil.equals(vecMsgHead, other.vecMsgHead) &&
			TarsUtil.equals(vecMsgData, other.vecMsgData) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iVersion, 0);
		_os.write(stUid, 1);
		_os.write(iGameID, 2);
		_os.write(sRoomID, 3);
		_os.write(iRoomServerID, 4);
		_os.write(iSequence, 5);
		_os.write(iFlag, 6);
		_os.write(vecMsgHead, 7);
		_os.write(vecMsgData, 8);
	}

	static TUid cache_stUid;
	static { 
		cache_stUid = new TUid();
	}
	static java.util.List<TMsgHead> cache_vecMsgHead;
	static { 
		cache_vecMsgHead = new java.util.ArrayList<TMsgHead>();
		TMsgHead var_1 = new TMsgHead();
		cache_vecMsgHead.add(var_1);
	}
	static java.util.List<byte[]> cache_vecMsgData;
	static { 
		cache_vecMsgData = new java.util.ArrayList<byte[]>();
		byte[] var_2 = new byte[1];
		byte var_3 = (byte)0;
		var_2[0] = var_3;
		cache_vecMsgData.add(var_2);
	}

	public void readFrom(TarsInputStream _is) {
		this.iVersion = _is.read(iVersion, 0, true);
		this.stUid = (TUid) _is.read(cache_stUid, 1, true);
		this.iGameID = _is.read(iGameID, 2, true);
		this.sRoomID = _is.readString(3, true);
		this.iRoomServerID = _is.read(iRoomServerID, 4, true);
		this.iSequence = _is.read(iSequence, 5, true);
		this.iFlag = _is.read(iFlag, 6, true);
		this.vecMsgHead = (java.util.List<TMsgHead>) _is.read(cache_vecMsgHead, 7, true);
		this.vecMsgData = (java.util.List<byte[]>) _is.read(cache_vecMsgData, 8, true);
	}

}
