// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.client.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TPlayerInfo {

	@TarsStructProperty(order = 0, isRequire = true)
	public long lUid = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public byte nState = (byte)0;
	@TarsStructProperty(order = 2, isRequire = true)
	public byte nChairNo = (byte)0;
	@TarsStructProperty(order = 3, isRequire = true)
	public String sNickName = "";
	@TarsStructProperty(order = 4, isRequire = true)
	public String sPortraitNo = "";
	@TarsStructProperty(order = 5, isRequire = true)
	public String sPortraitPath = "";
	@TarsStructProperty(order = 6, isRequire = true)
	public byte iSex = (byte)0;
	@TarsStructProperty(order = 7, isRequire = true)
	public String sIP = "";

	public long getLUid() {
		return lUid;
	}

	public void setLUid(long lUid) {
		this.lUid = lUid;
	}

	public byte getNState() {
		return nState;
	}

	public void setNState(byte nState) {
		this.nState = nState;
	}

	public byte getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	public String getSNickName() {
		return sNickName;
	}

	public void setSNickName(String sNickName) {
		this.sNickName = sNickName;
	}

	public String getSPortraitNo() {
		return sPortraitNo;
	}

	public void setSPortraitNo(String sPortraitNo) {
		this.sPortraitNo = sPortraitNo;
	}

	public String getSPortraitPath() {
		return sPortraitPath;
	}

	public void setSPortraitPath(String sPortraitPath) {
		this.sPortraitPath = sPortraitPath;
	}

	public byte getISex() {
		return iSex;
	}

	public void setISex(byte iSex) {
		this.iSex = iSex;
	}

	public String getSIP() {
		return sIP;
	}

	public void setSIP(String sIP) {
		this.sIP = sIP;
	}

	public TPlayerInfo() {
	}

	public TPlayerInfo(long lUid, byte nState, byte nChairNo, String sNickName, String sPortraitNo, String sPortraitPath, byte iSex, String sIP) {
		this.lUid = lUid;
		this.nState = nState;
		this.nChairNo = nChairNo;
		this.sNickName = sNickName;
		this.sPortraitNo = sPortraitNo;
		this.sPortraitPath = sPortraitPath;
		this.iSex = iSex;
		this.sIP = sIP;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(lUid);
		result = prime * result + TarsUtil.hashCode(nState);
		result = prime * result + TarsUtil.hashCode(nChairNo);
		result = prime * result + TarsUtil.hashCode(sNickName);
		result = prime * result + TarsUtil.hashCode(sPortraitNo);
		result = prime * result + TarsUtil.hashCode(sPortraitPath);
		result = prime * result + TarsUtil.hashCode(iSex);
		result = prime * result + TarsUtil.hashCode(sIP);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TPlayerInfo)) {
			return false;
		}
		TPlayerInfo other = (TPlayerInfo) obj;
		return (
			TarsUtil.equals(lUid, other.lUid) &&
			TarsUtil.equals(nState, other.nState) &&
			TarsUtil.equals(nChairNo, other.nChairNo) &&
			TarsUtil.equals(sNickName, other.sNickName) &&
			TarsUtil.equals(sPortraitNo, other.sPortraitNo) &&
			TarsUtil.equals(sPortraitPath, other.sPortraitPath) &&
			TarsUtil.equals(iSex, other.iSex) &&
			TarsUtil.equals(sIP, other.sIP) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(lUid, 0);
		_os.write(nState, 1);
		_os.write(nChairNo, 2);
		_os.write(sNickName, 3);
		_os.write(sPortraitNo, 4);
		_os.write(sPortraitPath, 5);
		_os.write(iSex, 6);
		_os.write(sIP, 7);
	}


	public void readFrom(TarsInputStream _is) {
		this.lUid = _is.read(lUid, 0, true);
		this.nState = _is.read(nState, 1, true);
		this.nChairNo = _is.read(nChairNo, 2, true);
		this.sNickName = _is.readString(3, true);
		this.sPortraitNo = _is.readString(4, true);
		this.sPortraitPath = _is.readString(5, true);
		this.iSex = _is.read(iSex, 6, true);
		this.sIP = _is.readString(7, true);
	}

}
