// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

public enum E_RETCODE {

	E_COMMON_SUCCESS(0);

	private final int value;

	private E_RETCODE(int value) {
		this.value = value;
	}

	public int value() {
		return this.value;
	}

	@Override
	public String toString() {
		return this.name() + ":" + this.value;
	}

	public static E_RETCODE convert(int value) {
		for(E_RETCODE v : values()) {
			if(v.value() == value) {
				return v;
			}
		}
		return null;
	}
}
