// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgNotifyDismissResult {

	@TarsStructProperty(order = 0, isRequire = true)
	public boolean dismiss = false;
	@TarsStructProperty(order = 1, isRequire = true)
	public byte reason = (byte)0;

	public boolean getDismiss() {
		return dismiss;
	}

	public void setDismiss(boolean dismiss) {
		this.dismiss = dismiss;
	}

	public byte getReason() {
		return reason;
	}

	public void setReason(byte reason) {
		this.reason = reason;
	}

	public TMsgNotifyDismissResult() {
	}

	public TMsgNotifyDismissResult(boolean dismiss, byte reason) {
		this.dismiss = dismiss;
		this.reason = reason;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(dismiss);
		result = prime * result + TarsUtil.hashCode(reason);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgNotifyDismissResult)) {
			return false;
		}
		TMsgNotifyDismissResult other = (TMsgNotifyDismissResult) obj;
		return (
			TarsUtil.equals(dismiss, other.dismiss) &&
			TarsUtil.equals(reason, other.reason) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(dismiss, 0);
		_os.write(reason, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.dismiss = _is.read(dismiss, 0, true);
		this.reason = _is.read(reason, 1, true);
	}

}
