// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgNotifySitDown {

	@TarsStructProperty(order = 0, isRequire = true)
	public long lUid = 0L;
	@TarsStructProperty(order = 1, isRequire = true)
	public byte nChairNo = (byte)0;

	public long getLUid() {
		return lUid;
	}

	public void setLUid(long lUid) {
		this.lUid = lUid;
	}

	public byte getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	public TMsgNotifySitDown() {
	}

	public TMsgNotifySitDown(long lUid, byte nChairNo) {
		this.lUid = lUid;
		this.nChairNo = nChairNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(lUid);
		result = prime * result + TarsUtil.hashCode(nChairNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgNotifySitDown)) {
			return false;
		}
		TMsgNotifySitDown other = (TMsgNotifySitDown) obj;
		return (
			TarsUtil.equals(lUid, other.lUid) &&
			TarsUtil.equals(nChairNo, other.nChairNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(lUid, 0);
		_os.write(nChairNo, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.lUid = _is.read(lUid, 0, true);
		this.nChairNo = _is.read(nChairNo, 1, true);
	}

}
