// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgReqEnterTable {

	@TarsStructProperty(order = 0, isRequire = true)
	public String sTableNo = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String sSign = "";
	@TarsStructProperty(order = 2, isRequire = true)
	public byte nRoomType = (byte)0;
	@TarsStructProperty(order = 3, isRequire = true)
	public byte nChairNo = 0;

	public String getSTableNo() {
		return sTableNo;
	}

	public void setSTableNo(String sTableNo) {
		this.sTableNo = sTableNo;
	}

	public String getSSign() {
		return sSign;
	}

	public void setSSign(String sSign) {
		this.sSign = sSign;
	}

	public byte getNRoomType() {
		return nRoomType;
	}

	public void setNRoomType(byte nRoomType) {
		this.nRoomType = nRoomType;
	}

	public byte getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	public TMsgReqEnterTable() {
	}

	public TMsgReqEnterTable(String sTableNo, String sSign, byte nRoomType, byte nChairNo) {
		this.sTableNo = sTableNo;
		this.sSign = sSign;
		this.nRoomType = nRoomType;
		this.nChairNo = nChairNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(sTableNo);
		result = prime * result + TarsUtil.hashCode(sSign);
		result = prime * result + TarsUtil.hashCode(nRoomType);
		result = prime * result + TarsUtil.hashCode(nChairNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgReqEnterTable)) {
			return false;
		}
		TMsgReqEnterTable other = (TMsgReqEnterTable) obj;
		return (
			TarsUtil.equals(sTableNo, other.sTableNo) &&
			TarsUtil.equals(sSign, other.sSign) &&
			TarsUtil.equals(nRoomType, other.nRoomType) &&
			TarsUtil.equals(nChairNo, other.nChairNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(sTableNo, 0);
		_os.write(sSign, 1);
		_os.write(nRoomType, 2);
		_os.write(nChairNo, 3);
	}


	public void readFrom(TarsInputStream _is) {
		this.sTableNo = _is.readString(0, true);
		this.sSign = _is.readString(1, true);
		this.nRoomType = _is.read(nRoomType, 2, true);
		this.nChairNo = _is.read(nChairNo, 3, true);
	}

}
