// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgReqVoteDismiss {

	@TarsStructProperty(order = 0, isRequire = true)
	public boolean support = false;

	public boolean getSupport() {
		return support;
	}

	public void setSupport(boolean support) {
		this.support = support;
	}

	public TMsgReqVoteDismiss() {
	}

	public TMsgReqVoteDismiss(boolean support) {
		this.support = support;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(support);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgReqVoteDismiss)) {
			return false;
		}
		TMsgReqVoteDismiss other = (TMsgReqVoteDismiss) obj;
		return (
			TarsUtil.equals(support, other.support) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(support, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.support = _is.read(support, 0, true);
	}

}
