// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgNotifyVoteDismiss {

	@TarsStructProperty(order = 0, isRequire = true)
	public boolean support = false;
	@TarsStructProperty(order = 1, isRequire = true)
	public byte nChairNo = (byte)0;

	public boolean getSupport() {
		return support;
	}

	public void setSupport(boolean support) {
		this.support = support;
	}

	public byte getNChairNo() {
		return nChairNo;
	}

	public void setNChairNo(byte nChairNo) {
		this.nChairNo = nChairNo;
	}

	public TMsgNotifyVoteDismiss() {
	}

	public TMsgNotifyVoteDismiss(boolean support, byte nChairNo) {
		this.support = support;
		this.nChairNo = nChairNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(support);
		result = prime * result + TarsUtil.hashCode(nChairNo);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgNotifyVoteDismiss)) {
			return false;
		}
		TMsgNotifyVoteDismiss other = (TMsgNotifyVoteDismiss) obj;
		return (
			TarsUtil.equals(support, other.support) &&
			TarsUtil.equals(nChairNo, other.nChairNo) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(support, 0);
		_os.write(nChairNo, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.support = _is.read(support, 0, true);
		this.nChairNo = _is.read(nChairNo, 1, true);
	}

}
