// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgRespAddict {

	@TarsStructProperty(order = 0, isRequire = true)
	public int iRetCode = 0;

	public int getIRetCode() {
		return iRetCode;
	}

	public void setIRetCode(int iRetCode) {
		this.iRetCode = iRetCode;
	}

	public TMsgRespAddict() {
	}

	public TMsgRespAddict(int iRetCode) {
		this.iRetCode = iRetCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(iRetCode);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgRespAddict)) {
			return false;
		}
		TMsgRespAddict other = (TMsgRespAddict) obj;
		return (
			TarsUtil.equals(iRetCode, other.iRetCode) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(iRetCode, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.iRetCode = _is.read(iRetCode, 0, true);
	}

}
