// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgNotifyTimeout {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nTimeout = (short)0;

	public short getNTimeout() {
		return nTimeout;
	}

	public void setNTimeout(short nTimeout) {
		this.nTimeout = nTimeout;
	}

	public TMsgNotifyTimeout() {
	}

	public TMsgNotifyTimeout(short nTimeout) {
		this.nTimeout = nTimeout;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nTimeout);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgNotifyTimeout)) {
			return false;
		}
		TMsgNotifyTimeout other = (TMsgNotifyTimeout) obj;
		return (
			TarsUtil.equals(nTimeout, other.nTimeout) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nTimeout, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.nTimeout = _is.read(nTimeout, 0, true);
	}

}
