// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.bzw.tars.server.tars.jfgameclientproto;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TMsgRespErrorCode {

	@TarsStructProperty(order = 0, isRequire = true)
	public short nErrorCode = (short)0;

	public short getNErrorCode() {
		return nErrorCode;
	}

	public void setNErrorCode(short nErrorCode) {
		this.nErrorCode = nErrorCode;
	}

	public TMsgRespErrorCode() {
	}

	public TMsgRespErrorCode(short nErrorCode) {
		this.nErrorCode = nErrorCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(nErrorCode);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TMsgRespErrorCode)) {
			return false;
		}
		TMsgRespErrorCode other = (TMsgRespErrorCode) obj;
		return (
			TarsUtil.equals(nErrorCode, other.nErrorCode) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(nErrorCode, 0);
	}


	public void readFrom(TarsInputStream _is) {
		this.nErrorCode = _is.read(nErrorCode, 0, true);
	}

}
